name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Workflow for build stage job(s)
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} 
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Azure Web App for Containers
      # You may pin to the exact commit or the version.
      # uses: FrodeHus/azwebapp-container-action@67da4c2bbf5b1382a6fd1adfc54f8b3bfb3ef270
      uses: FrodeHus/azwebapp-container-action@v1
      with:
        # Service Principal with Contributor role on the Web App
        service_principal: AZIOSP
        # Service Principal password
        service_principal_password: !4AIOAdminP@ss 
        # The tenant where all the web app resources are placed
        tenant: 47d93efa-1117-4577-bdcd-55fd4b3f011a
        # The name of the Azure Container Registry, minus the .azurecr.io
        registry: alphaio
        # Docker image name
        image: techchallenge01
        # Docker image tag
        tag: v1
        # Name of the Azure Web App for Containers instance
        webapp_name: aio-docker-webapp
        # Name of the resource group with the web app resides
        resource_group: aio-containers