name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Workflow for build stage job(s)
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

deploy:
  runs-on: ubuntu-latest
  needs: [build]
  if: ${{ github.ref == ‘refs/heads/master’ && github.event_name == ‘push’ }} 
  steps:
  - uses: actions/checkout@v2
  - name: Deploy to Docker registry
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: alphaio.azurecr.io/techchallengeapp
      tag_with_ref: true